version: '3'
services:
  rails:
    build: .
    volumes:
      - ./volume:/home/edimossilva/development/volume
      - ./config/gems:/home/edimossilva/.gems
      - ./config/bundle:/home/edimossilva/.bundle
      - ./config/bash/.bashrc:/home/edimossilva/.bashrc
      - ./config/bash/.bashhistory:/home/edimossilva/.bashhistory

    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      BUNDLE_PATH: "/home/edimossilva/.gems"
      HISTFILE: /home/edimossilva/.bashhistory


# docker-compose build
# docker-compose run -p 3000:3000 rails bash
# cd volume
# rails s -b 0.0.0.0