name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: |
          touch Dockerfile_rails.tar
          docker load < Dockerfile_rails.tar || 1
          docker build -f Dockerfile_rails . -t edimossilva/boilerplate
          docker save Dockerfile_rails > Dockerfile_rails.tar

      - name: start server
        run: docker-compose up -d

      - name: lint
        run: docker-compose exec -T boilerplate_server bundle exec rubocop

      - name: test
        run: |
          docker-compose exec -T boilerplate_server bundle exec rspec
